volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: sickmoqchima/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: sickmoqchima/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: sickmoqchima/kittygram_gateway
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - backend
      - frontend